version: '3'

services:
  server:
    container_name: nodejs
    build: '.' # especificando o diretório do DockerFile
    command: yarn start # comando para iniciar o serviço referente ao servidor
    ports:
      - '3333:3333' # especificando o mapeamento da porta da máquina local com a do container docker
    volumes:
      - ./home/node/app # espelhando todo o conteúdo do backend no docker excepto aqueles arquivos e pastas que constam no .dockerignore
    depends_on:
      - mongo # definindo a dependência em que o 'mongo' deve ser inicializado antes do 'node'
    links:
      - mongo
  mongo:
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
